/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container": "var(--md-surface-container)",
        "primary-fixed-dim": "#aac7ff",
        "surface-container-highest": "var(--md-surface-container-highest)",
        "primary-fixed": "#d7e3ff",
        "surface-dim": "#d1dbec",
        "on-secondary-fixed-variant": "#004883",
        "tertiary-container": "#006ab8",
        "tertiary": "#00528f",
        "primary-container": "#0066cc",
        "surface-tint": "#005cba",
        "outline-variant": "var(--md-outline-variant)",
        "outline": "var(--md-outline)",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "secondary": "#1960a6",
        "on-background": "var(--md-on-surface)",
        "error": "#ba1a1a",
        "surface-container-low": "var(--md-surface-container-low)",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001c38",
        "on-primary": "#ffffff",
        "surface": "var(--md-surface)",
        "secondary-fixed": "#d4e3ff",
        "inverse-primary": "#aac7ff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed": "#d2e4ff",
        "background": "var(--md-surface)",
        "surface-variant": "var(--md-surface-variant)",
        "on-surface-variant": "var(--md-on-surface-variant)",
        "primary": "var(--md-primary)",
        "on-surface": "var(--md-on-surface)",
        "on-tertiary-fixed-variant": "#004880",
        "on-tertiary-container": "#dbe9ff",
        "inverse-surface": "#27313e",
        "on-secondary-fixed": "#001c39",
        "tertiary-fixed-dim": "#a1c9ff",
        "surface-container-high": "var(--md-surface-container-high)",
        "on-secondary-container": "#00447e",
        "on-primary-fixed": "#001b3e",
        "error-container": "#ffdad6",
        "on-primary-container": "#dfe8ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#00458e",
        "secondary-container": "#7ab3ff",
        "secondary-fixed-dim": "#a4c9ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["'Plus Jakarta Sans'", "'Inter'", "sans-serif"],
        "body": ["'Inter'", "sans-serif"],
        "label": ["'Inter'", "sans-serif"]
      },
      boxShadow: {
        'glass': '0 4px 24px 0 rgba(31, 38, 135, 0.06)',
        'glass-hover': '0 8px 32px 0 rgba(31, 38, 135, 0.1)',
        'glass-dark': '0 4px 24px 0 rgba(0, 0, 0, 0.2)',
        'glass-dark-hover': '0 8px 32px 0 rgba(0, 0, 0, 0.3)',
        'glass-strong': '0 12px 40px 0 rgba(31, 38, 135, 0.08)',
        'soft': '0 2px 16px 0 rgba(0, 0, 0, 0.05)',
        'soft-lg': '0 4px 24px 0 rgba(0, 0, 0, 0.08)',
        'colored': '0 8px 24px -4px',
      },
      animation: {
        'blob': 'blob 10s infinite',
        'pulse-slow': 'pulse 6s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-up': 'fadeUp 0.5s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
      },
      keyframes: {
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
