// Defines the universal learning journey steps and achievement metadata
// used by the student engagement dashboard.

export const LEARNING_JOURNEY_STEPS = [
  {
    step: 1,
    key: 'skill_assessment',
    title: 'Skill Assessment',
    description: 'Discover your strengths and gaps',
    icon: 'Activity',
    route: '/skills',
    plan: 'Learn & Build',
    completionKey: 'hasSkillAssessment',
  },
  {
    step: 2,
    key: 'career_roadmap',
    title: 'Career Roadmap',
    description: 'Map your path to your dream role',
    icon: 'Map',
    route: '/career',
    plan: 'Learn & Build',
    completionKey: 'hasCareerRoadmap',
  },
  {
    step: 3,
    key: 'learning_path',
    title: 'Learning Path',
    description: 'Follow a structured curriculum',
    icon: 'Route',
    route: '/learning-paths',
    plan: 'Learn & Build',
    completionKey: 'hasLearningPath',
  },
  {
    step: 4,
    key: 'course_work',
    title: 'Course Work',
    description: 'Complete courses and build knowledge',
    icon: 'BookOpen',
    route: '/courses',
    plan: 'Learn & Build',
    completionKey: 'hasCourseProgress',
  },
  {
    step: 5,
    key: 'practice_projects',
    title: 'Practice & Projects',
    description: 'Build real-world portfolio projects',
    icon: 'Code2',
    route: '/coding-practice',
    plan: 'Learn & Build',
    completionKey: 'hasPractice',
  },
  {
    step: 6,
    key: 'profile_building',
    title: 'Profile Building',
    description: 'Optimize resume, LinkedIn & GitHub',
    icon: 'FileText',
    route: '/resume',
    plan: 'Tune & Polish',
    completionKey: 'hasProfile',
  },
  {
    step: 7,
    key: 'interview_prep',
    title: 'Interview Prep',
    description: 'Practice with AI mock interviews',
    icon: 'Zap',
    route: '/interview',
    plan: 'Zero to Hero',
    completionKey: 'hasInterviewPrep',
  },
  {
    step: 8,
    key: 'job_applications',
    title: 'Job Applications',
    description: 'Apply with confidence and track progress',
    icon: 'Briefcase',
    route: '/jobs',
    plan: 'Zero to Hero',
    completionKey: 'hasJobApplications',
  },
];

export const ACHIEVEMENT_DEFINITIONS = [
  { key: 'first_login', title: 'First Steps', description: 'Started your learning journey', icon: 'Footprints', color: 'bg-blue-500' },
  { key: 'first_resume', title: 'Resume Ready', description: 'Uploaded your first resume', icon: 'FileText', color: 'bg-emerald-500' },
  { key: 'first_assessment', title: 'Self Aware', description: 'Completed a skill assessment', icon: 'Activity', color: 'bg-violet-500' },
  { key: 'first_interview', title: 'Interview Warrior', description: 'Completed a mock interview', icon: 'Zap', color: 'bg-amber-500' },
  { key: 'streak_7', title: 'Week Warrior', description: '7-day learning streak', icon: 'Flame', color: 'bg-orange-500' },
  { key: 'streak_30', title: 'Monthly Master', description: '30-day learning streak', icon: 'Crown', color: 'bg-yellow-500' },
  { key: 'first_course', title: 'Course Champion', description: 'Completed a full course', icon: 'GraduationCap', color: 'bg-indigo-500' },
  { key: '5_tools', title: 'Explorer', description: 'Used 5 different tools', icon: 'Compass', color: 'bg-teal-500' },
  { key: '10_tools', title: 'Power User', description: 'Used 10 different tools', icon: 'Rocket', color: 'bg-rose-500' },
  { key: 'first_practice', title: 'Code Cruncher', description: 'Passed first coding challenge', icon: 'Code2', color: 'bg-green-500' },
  { key: 'profile_complete', title: 'Profile Pro', description: 'Complete professional profile', icon: 'BadgeCheck', color: 'bg-purple-500' },
];
