// GENERATED by run.mjs: verbatim copy of the module-scope guard in backend/src/middleware/auth.js (ADR 4.1).
const JWT_SECRET = process.env.JWT_SECRET;
if (!JWT_SECRET || JWT_SECRET.length < 32) {
  console.error('FATAL: JWT_SECRET must be set and at least 32 characters long');
  process.exit(1);
}

// Reaching this line means the guard did not stop module evaluation.
export const guardResult = {
  typeofProcess: typeof process,
  jwtSecretSeenAtModuleLoad: typeof JWT_SECRET === 'string' && JWT_SECRET.length > 0,
  jwtSecretLength: typeof JWT_SECRET === 'string' ? JWT_SECRET.length : null,
  guardPassed: true,
};
