// GENERATED by run.mjs from backend/src/routes/auth.js (regex slice) -- do not edit by hand.
import Joi from 'joi';

export const signupSchema = Joi.object({
  email: Joi.string().email().max(255).required(),
  password: Joi.string().min(8).max(128).required(),
  github_username: Joi.string().max(39).pattern(/^[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}$/i).allow('', null),
  linkedin_url: Joi.string().uri().max(500).allow('', null),
  deviceName: Joi.string().max(100).allow('', null),
});

export const loginSchema = Joi.object({
  email: Joi.string().email().max(255).required(),
  password: Joi.string().max(128).required(),
  replaceDevice: Joi.boolean(),
  deviceName: Joi.string().max(100).allow('', null),
});
