#!/usr/bin/env node
// Phase 0 spike harness: S7 bcryptjs, S8 joi, S9 jsonwebtoken, S10 crypto, E1 process.env/exit, E2 client IP.
//   Run from backend/:   node spike/auth/run.mjs
// Starts `wrangler dev --local` (only), waits for readiness, runs every check against Node references,
// writes spike/auth/out/results.json, prints a table, and ALWAYS kills every wrangler/workerd process it started.
// Uses only synthetic random secrets generated at runtime. Never reads backend/.env, never opens a database.
import { spawn, spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { createServer } from 'node:net';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import nodeCrypto from 'node:crypto';
import bcryptNative from 'bcrypt';      // native, Node reference (what prod runs today)
import bcryptjs from 'bcryptjs';        // same ESM build the Worker bundles
import jwt from 'jsonwebtoken';
import Joi from 'joi';

const HERE = dirname(fileURLToPath(import.meta.url));
const BACKEND = resolve(HERE, '../..');
const OUT = resolve(HERE, 'out');
const WRANGLER_JS = resolve(BACKEND, 'node_modules/wrangler/bin/wrangler.js');
const DEV_VARS = resolve(HERE, '.dev.vars');
mkdirSync(OUT, { recursive: true });

const results = { startedAt: new Date().toISOString(), node: process.version, S7: {}, S8: {}, S9: {}, S10: {}, E1: {}, E2: {}, S11: {}, notes: [] };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const median = (a) => { const s = [...a].sort((x, y) => x - y); return s[Math.floor(s.length / 2)]; };
const errShape = (e) => ({ name: e && e.name, message: e && e.message });

// ------------------------------------------------------------------------------------------------
// 0. Code generation: extract the REAL schemas / guard from the backend so nothing can drift.
// ------------------------------------------------------------------------------------------------
function generate() {
  const authSrc = readFileSync(resolve(BACKEND, 'src/routes/auth.js'), 'utf8');
  const sm = authSrc.match(/const signupSchema = Joi\.object\(\{[\s\S]*?\r?\n\}\);/);
  const lm = authSrc.match(/const loginSchema = Joi\.object\(\{[\s\S]*?\r?\n\}\);/);
  if (!sm || !lm) throw new Error('could not extract signupSchema/loginSchema from src/routes/auth.js');
  writeFileSync(resolve(HERE, 'generated-schemas.mjs'),
    `// GENERATED by run.mjs from backend/src/routes/auth.js (regex slice) -- do not edit by hand.\n` +
    `import Joi from 'joi';\n\n` +
    `export ${sm[0]}\n\nexport ${lm[0]}\n`);

  const mwSrc = readFileSync(resolve(BACKEND, 'src/middleware/auth.js'), 'utf8');
  const gm = mwSrc.match(/const JWT_SECRET = process\.env\.JWT_SECRET;[\s\S]*?process\.exit\(1\);\r?\n\}/);
  if (!gm) throw new Error('could not extract the JWT_SECRET guard from src/middleware/auth.js');
  writeFileSync(resolve(HERE, 'generated-guard.mjs'),
    `// GENERATED by run.mjs: verbatim copy of the module-scope guard in backend/src/middleware/auth.js (ADR 4.1).\n` +
    `${gm[0]}\n\n` +
    `// Reaching this line means the guard did not stop module evaluation.\n` +
    `export const guardResult = {\n` +
    `  typeofProcess: typeof process,\n` +
    `  jwtSecretSeenAtModuleLoad: typeof JWT_SECRET === 'string' && JWT_SECRET.length > 0,\n` +
    `  jwtSecretLength: typeof JWT_SECRET === 'string' ? JWT_SECRET.length : null,\n` +
    `  guardPassed: true,\n` +
    `};\n`);
  results.generated = { schemasBytes: sm[0].length + lm[0].length, guardBytes: gm[0].length };
}

// ------------------------------------------------------------------------------------------------
// Process management (Windows-aware). Only PIDs started here are ever killed.
// ------------------------------------------------------------------------------------------------
const started = new Set();
function descendants(rootPid) {
  try {
    const ps = spawnSync('powershell', ['-NoProfile', '-Command',
      'Get-CimInstance Win32_Process | Select-Object ProcessId,ParentProcessId | ConvertTo-Json -Compress'],
      { encoding: 'utf8', windowsHide: true });
    const rows = JSON.parse(ps.stdout);
    const kids = new Map();
    for (const r of rows) { (kids.get(r.ParentProcessId) || kids.set(r.ParentProcessId, []).get(r.ParentProcessId)).push(r.ProcessId); }
    const out = []; const stack = [rootPid];
    while (stack.length) { const p = stack.pop(); for (const c of kids.get(p) || []) { out.push(c); stack.push(c); } }
    return out;
  } catch { return []; }
}
const alive = (pid) => { try { process.kill(pid, 0); return true; } catch { return false; } };
function killTree(pid) {
  if (process.platform === 'win32') spawnSync('taskkill', ['/PID', String(pid), '/T', '/F'], { stdio: 'ignore', windowsHide: true });
  else { try { process.kill(pid, 'SIGKILL'); } catch { /* gone */ } }
}
async function stopWorker(w) {
  if (!w || w.stopped) return { leftover: [] };
  w.stopped = true;
  const kids = descendants(w.proc.pid);
  killTree(w.proc.pid);
  await sleep(800);
  let leftover = [w.proc.pid, ...kids].filter(alive);
  for (const p of leftover) killTree(p);   // these are all descendants of the wrangler we started
  await sleep(300);
  leftover = [w.proc.pid, ...kids].filter(alive);
  started.delete(w.proc.pid);
  return { pid: w.proc.pid, descendants: kids, leftover };
}
async function freePort(start) {
  for (let p = start; p < start + 60; p++) {
    const ok = await new Promise((res) => { const s = createServer(); s.once('error', () => res(false)); s.listen(p, '127.0.0.1', () => s.close(() => res(true))); });
    if (ok) return p;
  }
  throw new Error('no free port near ' + start);
}

async function startWorker({ config, script, label, basePort = 8788 }) {
  const port = await freePort(basePort);
  const inspector = await freePort(9330 + Math.floor(Math.random() * 200));
  const args = [WRANGLER_JS, 'dev'];
  if (script) args.push(script);
  args.push('--local', '--port', String(port), '--ip', '127.0.0.1', '--inspector-port', String(inspector),
    '-c', `spike/auth/${config}`, '--persist-to', 'spike/auth/out/.wrangler-state',
    '--show-interactive-dev-session', 'false', '--log-level', 'log');
  const env = { ...process.env, CLOUDFLARE_LOAD_DEV_VARS_FROM_DOT_ENV: 'false', WRANGLER_SEND_METRICS: 'false', NO_COLOR: '1', FORCE_COLOR: '0' };
  for (const k of ['DATABASE_URL', 'JWT_SECRET', 'NEON_DATABASE_URL']) delete env[k];
  const proc = spawn(process.execPath, args, { cwd: BACKEND, env, stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true });
  const w = { proc, port, label, logs: [], stopped: false, base: `http://127.0.0.1:${port}`, exited: false };
  started.add(proc.pid);
  const onData = (buf) => { for (const line of String(buf).split(/\r?\n/)) if (line.trim()) w.logs.push(line); };
  proc.stdout.on('data', onData); proc.stderr.on('data', onData);
  proc.on('exit', (code) => { w.exited = true; w.exitCode = code; });
  return w;
}
async function waitReady(w, path = '/health', timeoutMs = 150000) {
  const t0 = Date.now();
  while (Date.now() - t0 < timeoutMs) {
    if (w.exited) return { ready: false, exited: true, exitCode: w.exitCode };
    try {
      const r = await fetch(w.base + path, { signal: AbortSignal.timeout(4000) });
      const text = await r.text();
      return { ready: true, status: r.status, body: text.slice(0, 600), ms: Date.now() - t0 };
    } catch { await sleep(500); }
  }
  return { ready: false, timeout: true };
}
const tail = (w, n = 40) => w.logs.slice(-n);
const post = async (w, path, body, timeoutMs = 240000) => {
  const r = await fetch(w.base + path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body), signal: AbortSignal.timeout(timeoutMs) });
  const text = await r.text();
  try { return JSON.parse(text); } catch { throw new Error(`non-JSON ${r.status} from ${path}: ${text.slice(0, 300)}`); }
};
const getJson = async (w, path, headers = {}) => (await fetch(w.base + path, { headers, signal: AbortSignal.timeout(60000) })).json();

// ------------------------------------------------------------------------------------------------
// S7 bcryptjs
// ------------------------------------------------------------------------------------------------
const cls = (r) => (r.threw ? 'throw' : String(r.result));
async function nodeCompare(lib, pw, hash) {
  try { return { threw: false, result: await lib.compare(pw, hash) }; }
  catch (e) { return { threw: true, error: errShape(e) }; }
}
async function runS7(w) {
  const S = results.S7;
  // ---- password corpus (incl. unicode and the 72-byte bcrypt boundary) ----
  const P = [
    'password123', 'Correct Horse Battery Staple!', 'p@ss w0rd  with   spaces', "quote'\"back\\slash$2b$10$",
    'pässwörd-ünïcode', '日本語のパスワード', 'emoji-\u{1F510}\u{1F680}-pass', 'tab\tand\nnewline',
    'a'.repeat(71), 'a'.repeat(72), 'a'.repeat(73), 'a'.repeat(128),
    'x'.repeat(71) + 'é',            // 73 bytes, 2-byte char straddles the 72-byte cut
    'é'.repeat(36), 'é'.repeat(37),   // 72 / 74 bytes
    '€'.repeat(24), '€'.repeat(25),   // 72 / 75 bytes (3-byte chars)
    '\u{1F510}'.repeat(18), '\u{1F510}'.repeat(19), // 72 / 76 bytes (4-byte chars)
    'x'.repeat(70) + '日',            // 73 bytes, 3-byte char straddles the cut
  ];
  const t0 = Date.now();
  const nativeHashes = [];
  for (const p of P) nativeHashes.push(await bcryptNative.hash(p, await bcryptNative.genSalt(10)));
  const workerHashes = [];
  for (let i = 0; i < P.length; i += 5) {
    const r = await post(w, '/s7/hash', { passwords: P.slice(i, i + 5) });
    if (!r.hashes) throw new Error('/s7/hash failed: ' + JSON.stringify(r).slice(0, 300));
    workerHashes.push(...r.hashes);
  }
  S.generationMs = Date.now() - t0;
  S.workerHashPrefixes = [...new Set(workerHashes.map((h) => h.slice(0, 7)))];
  S.nativeHashPrefixes = [...new Set(nativeHashes.map((h) => h.slice(0, 7)))];
  const dupCheck = await post(w, '/s7/hash', { passwords: ['same-password-twice', 'same-password-twice'] });
  S.sameInputTwoHashesDiffer = dupCheck.hashes[0] !== dupCheck.hashes[1];

  const items = [];
  const add = (cat, label, password, hash, expected, gating = true) => items.push({ cat, label, password, hash, expected, gating });
  P.forEach((p, i) => add('A native->bcryptjs(worker)', `native hash of P[${i}]`, p, nativeHashes[i], true));
  P.forEach((p, i) => add('B bcryptjs(worker)->native', `worker hash of P[${i}]`, p, workerHashes[i], true));
  P.slice(0, 12).forEach((p, i) => { add('C wrong password', `wrong pw vs native hash P[${i}]`, '!' + p, nativeHashes[i], false); add('C wrong password', `wrong pw vs worker hash P[${i}]`, '!' + p, workerHashes[i], false); });
  // D: prefix handling. Same algorithm, different version markers.
  const base = nativeHashes[0];
  add('D prefix', '$2b$ (native default)', P[0], base, true);
  add('D prefix', '$2a$ rewrite of native hash', P[0], base.replace(/^\$2b\$/, '$2a$'), true);
  add('D2 $2y$ (informational)', '$2y$ rewrite of native hash', P[0], base.replace(/^\$2b\$/, '$2y$'), true, false);
  add('D prefix', '$2a$ rewrite of worker hash', P[0], workerHashes[0].replace(/^\$2b\$/, '$2a$'), true);
  add('D2 $2y$ (informational)', '$2y$ rewrite of worker hash', P[0], workerHashes[0].replace(/^\$2b\$/, '$2y$'), true, false);
  add('D prefix', '$2a$ hash, wrong pw', '!' + P[0], base.replace(/^\$2b\$/, '$2a$'), false);
  // D2: independent third-party vectors (crypt_blowfish test suite; produced by neither JS lib)
  add('D prefix', 'crypt_blowfish vector "U*U" ($2a$05)', 'U*U', '$2a$05$CCCCCCCCCCCCCCCCCCCCC.E5YPO9kmyuRGyh0XouQYb4YMJKvyOeW', true);
  add('D prefix', 'crypt_blowfish vector "U*U*" ($2a$05)', 'U*U*', '$2a$05$CCCCCCCCCCCCCCCCCCCCC.VGOzA784oUp/Z0DY336zx7pLYAy0lwK', true);
  add('D prefix', 'crypt_blowfish vector "U*U*U" ($2a$05)', 'U*U*U', '$2a$05$XXXXXXXXXXXXXXXXXXXXXOAcXxm9kjPGEMsLznoKqmqw7tc8WCx4a', true);
  add('D prefix', 'crypt_blowfish >72-byte vector', '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789chars after 72 are ignored', '$2a$05$abcdefghijklmnopqrstuu5s2v8.iXieOjg/.AySBTTZIIVFJeBui', true);
  // E: >72-byte truncation semantics must agree (silent truncation)
  add('E 72-byte truncation', "verify 'a'*72 against hash of 'a'*73 (native)", 'a'.repeat(72), nativeHashes[10], true);
  add('E 72-byte truncation', "verify 'a'*100 against hash of 'a'*72 (native)", 'a'.repeat(100), nativeHashes[9], true);
  add('E 72-byte truncation', "verify 'a'*72 against hash of 'a'*73 (worker)", 'a'.repeat(72), workerHashes[10], true);
  add('E 72-byte truncation', "verify 'a'*128 against hash of 'a'*72 (worker)", 'a'.repeat(128), workerHashes[9], true);
  add('E 72-byte truncation', "'x'*71+'é' (73B) vs 'x'*71 (71B) must NOT match (native)", 'x'.repeat(71), nativeHashes[12], 'same');
  // F: malformed hashes -> same behaviour class (true/false/throw) as Node native
  const bad = (label, hash) => add('F malformed hash (behaviour class)', label, 'password123', hash, 'same', false);
  bad('empty string', '');
  bad('plain junk', 'not-a-hash');
  bad('only prefix', '$2b$10$');
  bad('truncated by 1 char', base.slice(0, -1));
  bad('extra trailing char', base + 'A');
  bad('cost 99', base.replace('$10$', '$99$'));
  bad('cost 03 (below min)', base.replace('$10$', '$03$'));
  bad('invalid base64 char in hash body', base.slice(0, 40) + '!!!!!' + base.slice(45));
  bad('$2c$ version', base.replace(/^\$2b\$/, '$2c$'));
  bad('$2x$ version', base.replace(/^\$2b\$/, '$2x$'));
  bad('$1$ (md5-crypt style)', '$1$abcdefgh$4bdKm.e9gX9jjLrnrVJ6M.');
  bad('salt only, no digest', '$2b$10$' + 'A'.repeat(22));
  bad('60 x chars', 'x'.repeat(60));
  bad('null hash', null);
  bad('undefined hash', undefined);
  add('F malformed hash (behaviour class)', 'non-string password (number)', 12345678, base, 'same', false);
  add('F malformed hash (behaviour class)', 'null password', null, base, 'same', false);
  // G: exotic passwords (non-gating: not typeable, reported separately)
  add('G exotic (non-gating)', 'NUL byte inside password', 'abc\u0000def', null, 'same', false);
  add('G exotic (non-gating)', 'lone high surrogate', 'ab\ud800cd', null, 'same', false);
  add('G exotic (non-gating)', 'lone low surrogate', 'ab\udc00cd', null, 'same', false);

  // hashes for G items are produced by native so verification asks "does bcryptjs agree with native's own hash?"
  for (const it of items.filter((x) => x.cat.startsWith('G'))) {
    try { it.hash = await bcryptNative.hash(it.password, await bcryptNative.genSalt(10)); it.hashBy = 'native'; }
    catch (e) { it.hash = '$2b$10$' + 'A'.repeat(53); it.hashBy = 'native-threw:' + e.message; }
  }
  // extra G items: bcryptjs (worker) hashes them, native verifies
  const gPw = ['abc\u0000def', 'ab\ud800cd'];
  const gw = await post(w, '/s7/hash', { passwords: gPw });
  gPw.forEach((p, i) => add('G exotic (non-gating)', `worker hash of ${JSON.stringify(p)}`, p, gw.hashes[i], 'same', false));

  // evaluate: native (Node), bcryptjs (Node), bcryptjs (Worker)
  const workerRes = [];
  for (let i = 0; i < items.length; i += 15) {
    const r = await post(w, '/s7/verify', { items: items.slice(i, i + 15).map((x) => ({ password: x.password, hash: x.hash })) });
    if (!r.results) throw new Error('/s7/verify failed: ' + JSON.stringify(r).slice(0, 300));
    workerRes.push(...r.results);
  }
  const rows = [];
  for (let i = 0; i < items.length; i++) {
    const it = items[i];
    const n = await nodeCompare(bcryptNative, it.password, it.hash);
    const j = await nodeCompare(bcryptjs, it.password, it.hash);
    const wk = workerRes[i];
    const agree = cls(n) === cls(wk) && cls(j) === cls(wk);
    const meets = it.expected === 'same' ? true : cls(wk) === String(it.expected) && cls(n) === String(it.expected);
    rows.push({ cat: it.cat, label: it.label, gating: it.gating, expected: String(it.expected), native: cls(n), nodeBcryptjs: cls(j), workerBcryptjs: cls(wk),
      agree, meetsExpected: meets, pass: agree && meets,
      nativeErr: n.error && n.error.message, workerErr: wk.error && wk.error.message });
  }
  S.cases = rows;
  const core = rows.filter((r) => r.gating);
  S.total = rows.length; S.coreTotal = core.length;
  S.corePass = core.filter((r) => r.pass).length;
  S.gatingTotal = S.coreTotal; S.gatingPass = S.corePass;
  S.agreeAll = rows.filter((r) => r.agree).length;
  S.byCategory = {};
  for (const r of rows) { const c = (S.byCategory[r.cat] ||= { total: 0, pass: 0 }); c.total++; if (r.pass) c.pass++; }
  S.coreFailures = core.filter((r) => !r.pass);
  S.informationalDisagreements = rows.filter((r) => !r.gating && !r.pass).map((r) => ({ cat: r.cat, label: r.label, native: r.native, nodeBcryptjs: r.nodeBcryptjs, worker: r.workerBcryptjs, workerErr: r.workerErr }));
  const mal = rows.filter((r) => r.cat.startsWith('F'));
  S.malformed = { total: mal.length, sameClass: mal.filter((r) => r.agree).length,
    neverAccepts: mal.every((r) => r.native !== 'true' && r.workerBcryptjs !== 'true'),
    differing: mal.filter((r) => !r.agree).map((r) => ({ label: r.label, native: r.native, worker: r.workerBcryptjs, workerErr: r.workerErr })) };
  S.pass = S.corePass === S.coreTotal && S.sameInputTwoHashesDiffer;

  // ---- timing: cost-10 hash + compare in workerd (wall, measured from Node) vs Node ----
  const healthMs = [];
  for (let i = 0; i < 5; i++) { const t = performance.now(); await (await fetch(w.base + '/health')).text(); healthMs.push(performance.now() - t); }
  const tHash = [], tCmp = [], workerClock = [];
  let wh = workerHashes[0];
  for (let i = 0; i < 6; i++) {
    let t = performance.now();
    const r = await post(w, '/s7/hash', { passwords: ['timing-password-1'] });
    tHash.push(performance.now() - t); wh = r.hashes[0]; workerClock.push(r.workerClockMs[0]);
    t = performance.now();
    await post(w, '/s7/verify', { items: [{ password: 'timing-password-1', hash: wh }] });
    tCmp.push(performance.now() - t);
  }
  const nJs = { hash: [], cmp: [] }, nNat = { hash: [], cmp: [] };
  for (let i = 0; i < 6; i++) {
    let t = performance.now(); const h1 = await bcryptjs.hash('timing-password-1', await bcryptjs.genSalt(10)); nJs.hash.push(performance.now() - t);
    t = performance.now(); await bcryptjs.compare('timing-password-1', h1); nJs.cmp.push(performance.now() - t);
    t = performance.now(); const h2 = await bcryptNative.hash('timing-password-1', await bcryptNative.genSalt(10)); nNat.hash.push(performance.now() - t);
    t = performance.now(); await bcryptNative.compare('timing-password-1', h2); nNat.cmp.push(performance.now() - t);
  }
  const r1 = (a) => a.map((x) => Math.round(x));
  const summ = (a) => ({ samplesMs: r1(a), medianMs: Math.round(median(a)), minMs: Math.round(Math.min(...a)), maxMs: Math.round(Math.max(...a)) });
  S.timing = {
    note: 'wall ms measured from the Node harness (loopback HTTP included); first sample is a cold isolate/JIT. workerd clock (Date.now) is frozen during CPU work so in-worker timing is not meaningful.',
    healthRoundTrip: summ(healthMs),
    workerdBcryptjsHash_genSalt10_plus_hash: summ(tHash),
    workerdBcryptjsCompare: summ(tCmp),
    workerReportedClockMs_hash: workerClock,
    nodeBcryptjsHash: summ(nJs.hash), nodeBcryptjsCompare: summ(nJs.cmp),
    nodeNativeBcryptHash: summ(nNat.hash), nodeNativeBcryptCompare: summ(nNat.cmp),
  };
}

// ------------------------------------------------------------------------------------------------
// S8 joi
// ------------------------------------------------------------------------------------------------
async function runS8(w) {
  const S = results.S8;
  const { signupSchema, loginSchema } = await import('./generated-schemas.mjs');
  const pw = (n) => 'a'.repeat(n);
  const good = { email: 'user@example.com', password: 'password123' };
  const emailOfLength = (total) => { // local part 64 chars, domain of 63-char labels ending in .com
    let remain = total - 65 - 3; const labels = [];
    while (remain > 0) { const len = Math.max(1, Math.min(63, remain - 1)); labels.push('b'.repeat(len)); remain -= len + 1; }
    return `${'a'.repeat(64)}@${labels.join('.')}.com`;
  };
  const domainTo = emailOfLength;
  const withProto = JSON.parse('{"email":"user@example.com","password":"password123","__proto__":{"admin":true},"constructor":{"x":1}}');
  const signup = [
    ['baseline valid', good],
    ['email uppercase', { ...good, email: 'USER@EXAMPLE.COM' }],
    ['email plus tag + subdomain', { ...good, email: 'first.last+tag@mail.example.co.uk' }],
    ['email missing', { password: 'password123' }],
    ['email no @', { ...good, email: 'plainaddress' }],
    ['email no local', { ...good, email: '@example.com' }],
    ['email no domain', { ...good, email: 'user@' }],
    ['email double @', { ...good, email: 'user@@example.com' }],
    ['email no TLD', { ...good, email: 'user@example' }],
    ['email bogus TLD', { ...good, email: 'user@example.notarealtld123' }],
    ['email localhost', { ...good, email: 'user@localhost' }],
    ['email with space', { ...good, email: 'us er@example.com' }],
    ['email unicode local', { ...good, email: 'üser@example.com' }],
    ['email IDN domain', { ...good, email: 'user@exämple.com' }],
    ['email IP literal', { ...good, email: 'user@[127.0.0.1]' }],
    ['email quoted local', { ...good, email: '"john doe"@example.com' }],
    ['email number type', { ...good, email: 12345 }],
    ['email empty string', { ...good, email: '' }],
    ['email 254 chars', { ...good, email: domainTo(254) }],
    ['email 255 chars', { ...good, email: domainTo(255) }],
    ['email 256 chars', { ...good, email: domainTo(256) }],
    ['password 7', { ...good, password: pw(7) }],
    ['password 8', { ...good, password: pw(8) }],
    ['password 128', { ...good, password: pw(128) }],
    ['password 129', { ...good, password: pw(129) }],
    ['password missing', { email: good.email }],
    ['password empty', { ...good, password: '' }],
    ['password number', { ...good, password: 12345678 }],
    ['password 8 spaces', { ...good, password: '        ' }],
    ['password 8 emoji code points (16 UTF-16 units)', { ...good, password: '\u{1F510}'.repeat(8) }],
    ['password 4 emoji (8 UTF-16 units)', { ...good, password: '\u{1F510}'.repeat(4) }],
    ['github ok', { ...good, github_username: 'octocat' }],
    ['github single char', { ...good, github_username: 'a' }],
    ['github digit start', { ...good, github_username: '1abc' }],
    ['github inner hyphen', { ...good, github_username: 'a-b-c' }],
    ['github uppercase', { ...good, github_username: 'OctoCat' }],
    ['github 39 chars', { ...good, github_username: 'a' + '-b'.repeat(19) }],
    ['github 40 chars', { ...good, github_username: 'a'.repeat(40) }],
    ['github leading hyphen', { ...good, github_username: '-abc' }],
    ['github trailing hyphen', { ...good, github_username: 'abc-' }],
    ['github double hyphen', { ...good, github_username: 'a--b' }],
    ['github underscore', { ...good, github_username: 'a_b' }],
    ['github space', { ...good, github_username: 'a b' }],
    ['github unicode', { ...good, github_username: 'ünï' }],
    ['github empty string', { ...good, github_username: '' }],
    ['github null', { ...good, github_username: null }],
    ['github number', { ...good, github_username: 123 }],
    ['linkedin https', { ...good, linkedin_url: 'https://www.linkedin.com/in/some-person' }],
    ['linkedin http', { ...good, linkedin_url: 'http://example.com/x' }],
    ['linkedin no scheme', { ...good, linkedin_url: 'linkedin.com/in/x' }],
    ['linkedin ftp', { ...good, linkedin_url: 'ftp://example.com/x' }],
    ['linkedin javascript: uri', { ...good, linkedin_url: 'javascript:alert(1)' }],
    ['linkedin scheme only', { ...good, linkedin_url: 'https://' }],
    ['linkedin spaces', { ...good, linkedin_url: 'https://exa mple.com' }],
    ['linkedin 500 chars', { ...good, linkedin_url: 'https://example.com/' + 'a'.repeat(480) }],
    ['linkedin 501 chars', { ...good, linkedin_url: 'https://example.com/' + 'a'.repeat(481) }],
    ['linkedin empty', { ...good, linkedin_url: '' }],
    ['linkedin null', { ...good, linkedin_url: null }],
    ['deviceName 100', { ...good, deviceName: 'd'.repeat(100) }],
    ['deviceName 101', { ...good, deviceName: 'd'.repeat(101) }],
    ['deviceName empty', { ...good, deviceName: '' }],
    ['deviceName null', { ...good, deviceName: null }],
    ['deviceName number', { ...good, deviceName: 123 }],
    ['deviceName object', { ...good, deviceName: { a: 1 } }],
    ['unknown keys stripped', { ...good, admin: true, role: 'superuser', extra: { nested: [1, 2] } }],
    ['unknown keys + invalid known key', { ...good, password: 'short', admin: true }],
    ['__proto__/constructor own keys', withProto],
    ['multiple errors (abortEarly)', { email: 'bad', password: 'x', github_username: '-', linkedin_url: 'no' }],
    ['null body', null], ['string body', 'hello'], ['array body', []], ['number body', 42], ['empty object', {}],
  ];
  const login = [
    ['login baseline', { email: 'user@example.com', password: 'x' }],
    ['login password 128', { email: 'user@example.com', password: pw(128) }],
    ['login password 129', { email: 'user@example.com', password: pw(129) }],
    ['login password empty', { email: 'user@example.com', password: '' }],
    ['login password missing', { email: 'user@example.com' }],
    ['login email invalid', { email: 'nope', password: 'x' }],
    ['login replaceDevice true', { email: 'user@example.com', password: 'x', replaceDevice: true }],
    ['login replaceDevice false', { email: 'user@example.com', password: 'x', replaceDevice: false }],
    ['login replaceDevice "true" (string converts)', { email: 'user@example.com', password: 'x', replaceDevice: 'true' }],
    ['login replaceDevice "false"', { email: 'user@example.com', password: 'x', replaceDevice: 'false' }],
    ['login replaceDevice "TRUE"', { email: 'user@example.com', password: 'x', replaceDevice: 'TRUE' }],
    ['login replaceDevice "yes"', { email: 'user@example.com', password: 'x', replaceDevice: 'yes' }],
    ['login replaceDevice 1', { email: 'user@example.com', password: 'x', replaceDevice: 1 }],
    ['login replaceDevice null', { email: 'user@example.com', password: 'x', replaceDevice: null }],
    ['login replaceDevice object', { email: 'user@example.com', password: 'x', replaceDevice: {} }],
    ['login deviceName 100', { email: 'user@example.com', password: 'x', deviceName: 'd'.repeat(100) }],
    ['login deviceName 101', { email: 'user@example.com', password: 'x', deviceName: 'd'.repeat(101) }],
    ['login unknown keys stripped', { email: 'user@example.com', password: 'x', isAdmin: true, github_username: 'octocat' }],
    ['login null body', null],
    ['login empty object', {}],
  ];
  const nodeRun = (schema, input) => {
    const { error, value } = schema.validate(JSON.parse(JSON.stringify(input)), { stripUnknown: true });
    return {
      ok: !error, message: error ? error.details[0].message : null, errorMessage: error ? error.message : null,
      types: error ? error.details.map((d) => d.type) : null, paths: error ? error.details.map((d) => d.path.join('.')) : null,
      valueJson: JSON.stringify(value === undefined ? null : value),
    };
  };
  const rows = [];
  for (const [name, list, schema] of [['signup', signup, signupSchema], ['login', login, loginSchema]]) {
    const wr = await post(w, '/s8/validate', { schema: name, inputs: list.map((x) => x[1]) });
    if (!wr.results) throw new Error('/s8/validate failed: ' + JSON.stringify(wr).slice(0, 400));
    S.workerJoiVersion = wr.joiVersion;
    list.forEach(([label, input], i) => {
      const n = nodeRun(schema, input); const k = wr.results[i];
      const diffs = ['ok', 'message', 'errorMessage', 'types', 'paths', 'valueJson'].filter((f) => JSON.stringify(n[f]) !== JSON.stringify(k[f]));
      rows.push({ schema: name, label, nodeOk: n.ok, workerOk: k.ok, nodeMessage: n.message, workerMessage: k.message, diffs, pass: diffs.length === 0, nodeValue: n.valueJson });
    });
  }
  S.nodeJoiVersion = Joi.version;
  S.total = rows.length; S.passCount = rows.filter((r) => r.pass).length;
  S.acceptRejectAgree = rows.filter((r) => r.nodeOk === r.workerOk).length;
  S.messageAgree = rows.filter((r) => !r.diffs.includes('message')).length;
  S.strippedValueAgree = rows.filter((r) => !r.diffs.includes('valueJson')).length;
  S.nodeAccepts = rows.filter((r) => r.nodeOk).length;
  S.failures = rows.filter((r) => !r.pass);
  const sane = (label, ok) => rows.find((r) => r.label === label)?.nodeOk === ok;
  S.sanity = { baselineAccepted: sane('baseline valid', true), pw7Rejected: sane('password 7', false), pw8Accepted: sane('password 8', true), pw129Rejected: sane('password 129', false) };
  S.rows = rows;
  S.pass = S.passCount === S.total && Object.values(S.sanity).every(Boolean);
}

// ------------------------------------------------------------------------------------------------
// S9 jsonwebtoken
// ------------------------------------------------------------------------------------------------
async function runS9(w) {
  const S = results.S9;
  const secret = nodeCrypto.randomBytes(24).toString('hex');     // 48 chars, synthetic
  const wrongSecret = nodeCrypto.randomBytes(24).toString('hex');
  S.secretLength = secret.length;
  const payload = { id: 42, sessionId: 7 };
  const signOpts = { expiresIn: '15m', algorithm: 'HS256' };     // sessionService.js:107-111
  const verOpts = { algorithms: ['HS256'] };                      // middleware/auth.js:18
  const b64u = (o) => Buffer.from(typeof o === 'string' ? o : JSON.stringify(o)).toString('base64url');
  const now = Math.floor(Date.now() / 1000);

  // Worker-signed tokens
  const ws = await post(w, '/s9/sign', { cases: [
    { payload, secret, options: signOpts },
    { payload, secret, options: { expiresIn: '7d', algorithm: 'HS256' } },
    { payload: { ...payload, exp: now - 10 }, secret, options: { algorithm: 'HS256' } },        // already expired
    { payload: { ...payload, iat: 1700000000, exp: 1900000000 }, secret, options: { algorithm: 'HS256' } }, // deterministic
    { payload, secret, options: { expiresIn: '15m', algorithm: 'HS512' } },
  ] });
  if (!ws.results || ws.results.some((r) => !r.ok)) throw new Error('worker jwt.sign failed: ' + JSON.stringify(ws).slice(0, 500));
  const [wTok, wTok7d, wExpired, wDet, wHS512] = ws.results.map((r) => r.token);
  const decode = (t) => JSON.parse(Buffer.from(t.split('.')[1], 'base64url').toString());

  const nTok = jwt.sign(payload, secret, signOpts);
  const nExpired = jwt.sign({ ...payload, exp: now - 10 }, secret, { algorithm: 'HS256' });
  const nDet = jwt.sign({ ...payload, iat: 1700000000, exp: 1900000000 }, secret, { algorithm: 'HS256' });
  const nHS512 = jwt.sign(payload, secret, { expiresIn: '15m', algorithm: 'HS512' });
  const nHS384 = jwt.sign(payload, secret, { expiresIn: '15m', algorithm: 'HS384' });
  const pl = { id: 42, sessionId: 7, iat: now, exp: now + 900 };
  const noneTok = `${b64u({ alg: 'none', typ: 'JWT' })}.${b64u(pl)}.`;
  const noneCap = `${b64u({ alg: 'None', typ: 'JWT' })}.${b64u(pl)}.`;
  const noneWithSig = `${b64u({ alg: 'none', typ: 'JWT' })}.${b64u(pl)}.${'A'.repeat(43)}`;
  // RS256 header but HMAC-signed with the secret (algorithm-confusion style)
  const rsHeader = b64u({ alg: 'RS256', typ: 'JWT' });
  const rsBody = b64u(pl);
  const rsTok = `${rsHeader}.${rsBody}.${nodeCrypto.createHmac('sha256', secret).update(`${rsHeader}.${rsBody}`).digest('base64url')}`;
  const [h, p, s] = nTok.split('.');
  const tampered = `${h}.${b64u({ ...payload, id: 1 })}.${s}`;
  const nbf = jwt.sign({ ...payload, nbf: now + 3600 }, secret, { expiresIn: '2h', algorithm: 'HS256' });

  const cases = [
    { id: 'C1 node-signed verified (worker+node)', token: nTok, secret, options: verOpts, expect: { ok: true } },
    { id: 'C2 worker-signed verified (worker+node)', token: wTok, secret, options: verOpts, expect: { ok: true } },
    { id: 'C3a node-signed, wrong secret', token: nTok, secret: wrongSecret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C3b worker-signed, wrong secret', token: wTok, secret: wrongSecret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C4a alg:none, empty signature', token: noneTok, secret, options: verOpts, expect: { ok: false } },
    { id: 'C4b alg:None (case), empty signature', token: noneCap, secret, options: verOpts, expect: { ok: false } },
    { id: 'C4c alg:none with junk signature', token: noneWithSig, secret, options: verOpts, expect: { ok: false } },
    { id: 'C5a HS512 token, algorithms:[HS256] (node-signed)', token: nHS512, secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C5b HS512 token, algorithms:[HS256] (worker-signed)', token: wHS512, secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C5c HS384 token, algorithms:[HS256]', token: nHS384, secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C5d control: HS512 token, algorithms:[HS512] ok', token: nHS512, secret, options: { algorithms: ['HS512'] }, expect: { ok: true } },
    { id: 'C5e RS256-header/HMAC-signed, algorithms:[HS256]', token: rsTok, secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C6a expired (node-signed)', token: nExpired, secret, options: verOpts, expect: { ok: false, name: 'TokenExpiredError' } },
    { id: 'C6b expired (worker-signed)', token: wExpired, secret, options: verOpts, expect: { ok: false, name: 'TokenExpiredError' } },
    { id: 'C7 tampered payload', token: tampered, secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C8a malformed "abc"', token: 'abc', secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C8b malformed "a.b"', token: 'a.b', secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C8c malformed 4 parts', token: 'a.b.c.d', secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C8d empty token', token: '', secret, options: verOpts, expect: { ok: false, name: 'JsonWebTokenError' } },
    { id: 'C9 nbf in future', token: nbf, secret, options: verOpts, expect: { ok: false, name: 'NotBeforeError' } },
    { id: 'C10 worker-signed 7d verified', token: wTok7d, secret, options: verOpts, expect: { ok: true } },
    { id: 'C11 deterministic token (node-signed)', token: nDet, secret, options: verOpts, expect: { ok: true } },
  ];
  const nodeVerify = (c) => { try { return { ok: true, payload: jwt.verify(c.token, c.secret, c.options) }; } catch (e) { return { ok: false, error: errShape(e) }; } };
  const wv = await post(w, '/s9/verify', { cases: cases.map((c) => ({ token: c.token, secret: c.secret, options: c.options })) });
  if (!wv.results) throw new Error('/s9/verify failed: ' + JSON.stringify(wv).slice(0, 400));
  const rows = cases.map((c, i) => {
    const n = nodeVerify(c); const k = wv.results[i];
    const sameOutcome = n.ok === k.ok && (n.ok ? JSON.stringify(n.payload) === JSON.stringify(k.payload)
      : n.error.name === k.error.name && n.error.message === k.error.message);
    const meets = c.expect.ok === k.ok && c.expect.ok === n.ok && (!c.expect.name || (k.error && k.error.name === c.expect.name && n.error.name === c.expect.name));
    return { id: c.id, expected: JSON.stringify(c.expect), node: n.ok ? 'accepted' : `${n.error.name}: ${n.error.message}`,
      worker: k.ok ? 'accepted' : `${k.error.name}: ${k.error.message}`, sameOutcome, meetsExpectation: meets, pass: sameOutcome && meets };
  });
  // extra assertions
  const extra = [];
  const chk = (id, pass, detail) => extra.push({ id, pass, detail });
  chk('X1 worker-signed token has HS256 header', JSON.parse(Buffer.from(wTok.split('.')[0], 'base64url').toString()).alg === 'HS256', wTok.split('.')[0]);
  const wp = decode(wTok);
  chk("X2 worker expiresIn '15m' => exp-iat == 900", wp.exp - wp.iat === 900, `iat=${wp.iat} exp=${wp.exp}`);
  const w7 = decode(wTok7d);
  chk("X3 worker expiresIn '7d' => exp-iat == 604800", w7.exp - w7.iat === 604800, `${w7.exp - w7.iat}`);
  chk('X4 worker iat within 30s of harness clock', Math.abs(wp.iat - now) <= 30, `worker iat ${wp.iat} vs harness ${now}`);
  chk('X5 deterministic HS256 token: node == worker (byte-identical)', nDet === wDet, `node ${nDet.slice(-16)} worker ${wDet.slice(-16)}`);
  chk('X6 worker-signed payload has exactly {id,sessionId,iat,exp}', JSON.stringify(Object.keys(wp).sort()) === JSON.stringify(['exp', 'iat', 'id', 'sessionId']), JSON.stringify(wp));
  S.cases = rows; S.extra = extra;
  S.total = rows.length + extra.length;
  S.passCount = rows.filter((r) => r.pass).length + extra.filter((x) => x.pass).length;
  S.failures = [...rows.filter((r) => !r.pass), ...extra.filter((x) => !x.pass)];
  S.pass = S.passCount === S.total;
  S.limitation = 'No prod-issued token or prod JWT_SECRET was available; "Node-signed" tokens use the same jsonwebtoken 9.0.3 + same options as sessionService.js, with a synthetic secret.';
}

// ------------------------------------------------------------------------------------------------
// S10 crypto
// ------------------------------------------------------------------------------------------------
async function runS10(w) {
  const S = results.S10;
  const inputs = ['', 'abc', 'hello world', 'ünïcödé 日本語 \u{1F510}', 'a'.repeat(1_000_000), nodeCrypto.randomBytes(48).toString('hex'),
    `${b64('{"alg":"HS256"}')}.${b64('{"id":1}')}.sig`, 'ab\ud800cd', 'line1\nline2\r\n', ' leading and trailing '];
  function b64(s) { return Buffer.from(s).toString('base64url'); }
  const aiCacheInputs = [['You are a coach', 'Explain closures', 2000, 0.7], ['', '', null, null], ['sys|with|pipes', 'user \u{1F510}', 1500, 0.2]];
  const bufferHexInputs = [nodeCrypto.randomBytes(32).toString('hex'), '00', 'ff'.repeat(100)];
  const wr = await post(w, '/s10', { inputs, aiCacheInputs, bufferHexInputs });
  if (!wr.hashes) throw new Error('/s10 failed: ' + JSON.stringify(wr).slice(0, 400));
  const rows = [];
  const nodeHash = (t) => nodeCrypto.createHash('sha256').update(t).digest('hex');
  inputs.forEach((s, i) => rows.push({ id: `sha256 input#${i} (${s.length} chars)`, pass: nodeHash(s) === wr.hashes[i] }));
  aiCacheInputs.forEach((a, i) => rows.push({ id: `aiCache key#${i}`, pass: nodeCrypto.createHash('sha256').update(`${a[0]}|${a[1]}|${a[2]}|${a[3]}`).digest('hex').slice(0, 16) === wr.aiKeys[i] }));
  bufferHexInputs.forEach((h, i) => rows.push({ id: `sha256 Buffer input#${i}`, pass: nodeCrypto.createHash('sha256').update(Buffer.from(h, 'hex')).digest('hex') === wr.bufHash[i] }));
  const r = wr.random;
  rows.push({ id: 'randomBytes(48).toString(hex) length 96 (x2)', pass: r.r1len === 96 && r.r2len === 96 });
  rows.push({ id: 'two randomBytes calls differ', pass: r.differ });
  rows.push({ id: 'output is 96 lowercase hex chars', pass: r.hexOnly });
  rows.push({ id: '500 randomBytes(48) calls all unique', pass: r.unique500 === 500 });
  S.rows = rows; S.total = rows.length; S.passCount = rows.filter((x) => x.pass).length; S.pass = S.passCount === S.total;
  S.failures = rows.filter((x) => !x.pass);
}

// ------------------------------------------------------------------------------------------------
// E1 / E2 / S11 gate
// ------------------------------------------------------------------------------------------------
async function runE1Main(w) {
  const first = await getJson(w, '/e1');
  const beforeLogs = w.logs.length;
  let exitRes, exitErr = null;
  try {
    const rr = await fetch(w.base + '/e1/exit', { method: 'POST', signal: AbortSignal.timeout(30000) });
    const txt = await rr.text();
    let parsed = null; try { parsed = JSON.parse(txt); } catch { /* not JSON */ }
    exitRes = { httpStatus: rr.status, bodyIsHandlerJson: !!parsed, handlerCatchBlockRan: !!(parsed && parsed.outcome), bodyPrefix: txt.slice(0, 160), parsed };
  } catch (e) { exitErr = String(e.message || e); }
  await sleep(500);
  let after = null, afterErr = null;
  try { after = await getJson(w, '/e1'); } catch (e) { afterErr = String(e.message || e); }
  return {
    moduleLoad: first.moduleLoad, requestTime: first.requestTime, instanceIdFirst: first.instanceId,
    exitCall: exitRes || { fetchError: exitErr },
    afterExit: after ? { instanceIdSame: after.instanceId === first.instanceId, requestCounter: after.requestCounter, moduleLoadedAtSame: after.moduleLoadedAt === first.moduleLoadedAt } : { error: afterErr },
    workerStillServing: !!after, logsDuringExit: w.logs.slice(beforeLogs).slice(0, 25),
  };
}

async function runE1Static(label, config, jwtPresent) {
  const secretLine = jwtPresent ? `JWT_SECRET=${nodeCrypto.randomBytes(24).toString('hex')}\n` : '';
  writeFileSync(DEV_VARS, `SPIKE_SYNTH_SECRET=${nodeCrypto.randomBytes(24).toString('hex')}\n${secretLine}`);
  const w = await startWorker({ config, script: 'spike/auth/e1-static.mjs', label, basePort: 8800 });
  let ready, res = null;
  try {
    ready = await waitReady(w, '/', 90000);
    res = { ready: ready.ready, status: ready.status, body: ready.body, exited: ready.exited, timeout: ready.timeout };
  } finally {
    res = res || {};
    res.label = label; res.config = config; res.jwtSecretProvided = jwtPresent;
    res.logs = w.logs.filter((l) => /FATAL|exit|Error|error|Uncaught|warn|compatib/i.test(l)).slice(0, 12);
    res.stop = await stopWorker(w);
  }
  return res;
}

// ------------------------------------------------------------------------------------------------
async function main() {
  generate();
  const synthSecret = nodeCrypto.randomBytes(24).toString('hex');
  writeFileSync(DEV_VARS, `SPIKE_SYNTH_SECRET=${synthSecret}\n`); // synthetic only; also blocks any .env fallback
  const workers = [];
  try {
    // ---- main worker: S7-S10, E1 (default config), E2, S11 gate ----
    const w = await startWorker({ config: 'wrangler.toml', label: 'main' });
    workers.push(w);
    const ready = await waitReady(w);
    results.workerMain = { port: w.port, ready };
    if (!ready.ready) throw new Error('main worker not ready: ' + JSON.stringify(ready) + '\n' + tail(w).join('\n'));
    results.workerMain.startupLogHints = w.logs.filter((l) => /compatib|Ready|warn|WARN|nodejs_compat/i.test(l)).slice(0, 10);
    const keys = await getJson(w, '/envkeys');
    results.workerMain.envBindingNames = keys.envBindingNames;
    if (keys.envBindingNames.some((k) => ['DATABASE_URL', 'JWT_SECRET'].includes(k))) throw new Error('ABORT: worker env unexpectedly contains DATABASE_URL/JWT_SECRET');

    for (const [name, fn] of [['S7', runS7], ['S8', runS8], ['S9', runS9], ['S10', runS10]]) {
      try { await fn(w); }
      catch (e) { results[name].pass = false; results[name].harnessError = String(e && e.stack || e).split('\n').slice(0, 6).join('\n'); }
    }
    try { results.E1.default = await runE1Main(w); } catch (e) { results.E1.default = { harnessError: String(e) }; }

    // E2
    try {
      const a = await getJson(w, '/e2');
      const b = await getJson(w, '/e2', { 'CF-Connecting-IP': '9.9.9.9' });
      results.E2 = { noHeader: a, clientSuppliedHeader: b.cfConnectingIp };
    } catch (e) { results.E2 = { harnessError: String(e) }; }

    // S11 gate only (no DATABASE_URL => skipped, no connection). The Neon code itself is NOT executed.
    try { const r = await fetch(w.base + '/s11'); results.S11 = { status: r.status, body: await r.json() }; }
    catch (e) { results.S11 = { harnessError: String(e) }; }

    results.workerMain.stop = await stopWorker(w);

    // ---- E1 variants (module-load / request-time process.env + process.exit) ----
    results.E1.variants = {};
    for (const [label, config] of [['nodejs_compat_populate_process_env', 'wrangler.populate.toml'],
      ['nodejs_compat_do_not_populate_process_env', 'wrangler.nopopulate.toml'], ['compat_date_2024-09-23', 'wrangler.olddate.toml']]) {
      const wv = await startWorker({ config, label });
      try {
        const rd = await waitReady(wv);
        if (!rd.ready) { results.E1.variants[label] = { notReady: rd, logs: tail(wv, 15) }; continue; }
        const r = await runE1Main(wv);
        r.startupLogHints = wv.logs.filter((l) => /compatib|WARN|warn/i.test(l)).slice(0, 4);
        results.E1.variants[label] = r;
      } catch (e) { results.E1.variants[label] = { harnessError: String(e) }; }
      finally { results.E1.variants[label] = { ...(results.E1.variants[label] || {}), stop: await stopWorker(wv) }; }
    }

    // ---- E1 static import: ADR 4.1 guard as a module-scope import ----
    results.E1.staticGuard = [];
    for (const [label, config, present] of [
      ['default config, JWT_SECRET provided as secret', 'wrangler.toml', true],
      ['default config, JWT_SECRET absent', 'wrangler.toml', false],
      ['populate flag, JWT_SECRET provided', 'wrangler.populate.toml', true],
      ['do_not_populate flag, JWT_SECRET provided', 'wrangler.nopopulate.toml', true],
      ['compat 2024-09-23, JWT_SECRET provided', 'wrangler.olddate.toml', true],
    ]) {
      try { results.E1.staticGuard.push(await runE1Static(label, config, present)); }
      catch (e) { results.E1.staticGuard.push({ label, harnessError: String(e) }); }
    }
    // ---- E1 derived summary (facts only) ----
    try {
      const d = results.E1.default, v = results.E1.variants, g = results.E1.staticGuard;
      const seen = (x) => !!x && x.moduleLoad && x.moduleLoad.SPIKE_VAR === 'hello' && x.moduleLoad.SPIKE_SYNTH_SECRET_present && x.requestTime.SPIKE_VAR === 'hello' && x.requestTime.SPIKE_SYNTH_SECRET_present;
      results.E1.summary = {
        processEnvPopulatedAtModuleLoadAndRequestTime: {
          'default (2026-09-14 + nodejs_compat)': seen(d),
          'nodejs_compat_populate_process_env': seen(v.nodejs_compat_populate_process_env),
          'nodejs_compat_do_not_populate_process_env': seen(v.nodejs_compat_do_not_populate_process_env),
          'compat_date_2024-09-23 + nodejs_compat': seen(v['compat_date_2024-09-23']),
        },
        handlerProcessExit: d && d.exitCall && { httpStatus: d.exitCall.httpStatus, catchable: d.exitCall.handlerCatchBlockRan, isolateSurvived: d.afterExit && d.afterExit.instanceIdSame },
        moduleLoadGuardWhenSecretAbsent: g.filter((x) => !x.jwtSecretProvided).map((x) => ({ label: x.label, workerLoaded: /"loaded":true/.test(x.body || ''), guardContinuedPastExit: /"guardPassed":true/.test(x.body || '') })),
        moduleLoadGuardWhenSecretProvided: g.filter((x) => x.jwtSecretProvided).map((x) => ({ label: x.label, secretSeenAtModuleLoad: /"jwtSecretSeenAtModuleLoad":true/.test(x.body || ''), workerLoaded: /"loaded":true/.test(x.body || '') })),
      };
    } catch (e) { results.E1.summary = { error: String(e) }; }
  } finally {
    for (const w of workers) await stopWorker(w).catch(() => {});
    try { rmSync(DEV_VARS, { force: true }); } catch { /* ignore */ }
    for (const pid of [...started]) { killTree(pid); started.delete(pid); }
    results.finishedAt = new Date().toISOString();
    writeFileSync(resolve(OUT, 'results.json'), JSON.stringify(results, null, 2));
  }
  printTable();
}

function printTable() {
  const S7 = results.S7, S8 = results.S8, S9 = results.S9, S10 = results.S10;
  const pf = (b) => (b ? 'PASS' : 'FAIL');
  console.log('\n==== Phase 0 spike results (S7-S10, E1, E2) ====');
  console.log(`S7  bcryptjs   ${pf(S7.pass)}  core (a-e) ${S7.corePass}/${S7.coreTotal} agree+correct across node bcrypt / node bcryptjs / worker bcryptjs; ${S7.agreeAll}/${S7.total} agree overall incl. informational`);
  if (S7.malformed) console.log(`      malformed-hash behaviour class same as native: ${S7.malformed.sameClass}/${S7.malformed.total}; neither ever returns true: ${S7.malformed.neverAccepts}`);
  if (S7.byCategory) for (const [c, v] of Object.entries(S7.byCategory)) console.log(`      ${c.padEnd(30)} ${v.pass}/${v.total}`);
  if (S7.informationalDisagreements && S7.informationalDisagreements.length) console.log('      informational disagreements:', JSON.stringify(S7.informationalDisagreements));
  if (S7.timing) {
    const t = S7.timing;
    console.log(`      workerd hash(genSalt10+hash) median ${t.workerdBcryptjsHash_genSalt10_plus_hash.medianMs} ms [${t.workerdBcryptjsHash_genSalt10_plus_hash.samplesMs}], compare median ${t.workerdBcryptjsCompare.medianMs} ms [${t.workerdBcryptjsCompare.samplesMs}], health RTT ${t.healthRoundTrip.medianMs} ms`);
    console.log(`      node bcryptjs hash ${t.nodeBcryptjsHash.medianMs} ms / cmp ${t.nodeBcryptjsCompare.medianMs} ms; node native hash ${t.nodeNativeBcryptHash.medianMs} ms / cmp ${t.nodeNativeBcryptCompare.medianMs} ms`);
  }
  console.log(`S8  joi        ${pf(S8.pass)}  ${S8.passCount}/${S8.total} inputs identical (accept/reject ${S8.acceptRejectAgree}/${S8.total}, message ${S8.messageAgree}/${S8.total}, stripped value ${S8.strippedValueAgree}/${S8.total}); joi node ${S8.nodeJoiVersion} worker ${S8.workerJoiVersion}`);
  console.log(`S9  jsonwebtoken ${pf(S9.pass)}  ${S9.passCount}/${S9.total} checks (node vs worker, expectations)`);
  console.log(`S10 crypto     ${pf(S10.pass)}  ${S10.passCount}/${S10.total} checks`);
  const d = results.E1.default;
  if (d && d.moduleLoad) {
    console.log(`E1  default: module-load typeof process=${d.moduleLoad.typeofProcess} exit=${d.moduleLoad.typeofProcessExit} SPIKE_VAR=${d.moduleLoad.SPIKE_VAR} secretPresent=${d.moduleLoad.SPIKE_SYNTH_SECRET_present} | request-time SPIKE_VAR=${d.requestTime.SPIKE_VAR} secretPresent=${d.requestTime.SPIKE_SYNTH_SECRET_present}`);
    console.log(`    process.exit(1) in handler: HTTP ${d.exitCall.httpStatus}, handler try/catch ran=${d.exitCall.handlerCatchBlockRan}, body=${d.exitCall.bodyPrefix}; isolate survived=${d.afterExit.instanceIdSame}`);
  }
  for (const [k, v] of Object.entries(results.E1.variants || {})) if (v.moduleLoad) console.log(`    variant ${k}: module-load SPIKE_VAR=${v.moduleLoad.SPIKE_VAR} secret=${v.moduleLoad.SPIKE_SYNTH_SECRET_present}; request-time SPIKE_VAR=${v.requestTime.SPIKE_VAR} secret=${v.requestTime.SPIKE_SYNTH_SECRET_present}; exit -> HTTP ${v.exitCall.httpStatus} catchRan=${v.exitCall.handlerCatchBlockRan}`);
  for (const g of results.E1.staticGuard || []) console.log(`    static guard [${g.label}]: status=${g.status} ready=${g.ready} body=${(g.body || '').slice(0, 160)}`);
  console.log(`E2  ${JSON.stringify(results.E2.noHeader || results.E2).slice(0, 300)}`);
  console.log(`S11 gate ${JSON.stringify(results.S11.body || results.S11).slice(0, 300)}`);
  console.log('\nFull details: spike/auth/out/results.json');
}

process.on('SIGINT', () => { for (const pid of started) killTree(pid); try { rmSync(DEV_VARS, { force: true }); } catch { /* */ } process.exit(130); });
process.on('exit', () => { for (const pid of started) killTree(pid); });
main().catch((e) => { console.error('HARNESS ERROR', e); process.exitCode = 1; });
